name: Format Python Code
on:
    push:
    pull_request:
        branches:
          - main
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        uses: ./
        with:
          args: --recursive --in-place --aggressive --aggressive .
